### ISSUE TITLE
Replace tokio-core dependencies with tokio ones

### ISSUE THREAD

**Issue by igor-103** [tailhook/tk-listen#1]
It seems that the newest version of [tokio-core](https://docs.rs/crate/tokio-core/0.1.16) is going to be deprecated in the favour of [tokio](https://crates.io/crates/tokio) itself. Thus the _tk-listen_ should have alll `tokio-core` dependencies replaced with `tokio` ones. If you agree I may provide the corresponding pull request then.

**Comment by tailhook** [comment]
Yes, let's do it. I was going to wait for futures 0.2. But if you need it now, we can release tk-listen 0.2 for tokio 0.1 and then bump to 0.3 for tokio 0.2, it's not that versions are scarce resource :)

So, yes go ahead and make PR.
